version: '3.3'

services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=time_convert_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: